### ISSUE TITLE
Non-transparent glass

### ISSUE THREAD

**Issue by AlterShiki** [ItsEasyActually/AutoDemo_SpeedHighway#1]
![sonic_2019-03-03_17-58-16](https://user-images.githubusercontent.com/42754652/53697832-2a1ba680-3dde-11e9-940c-f8453f8227c0.jpg)
![sonic_2019-03-03_17-57-09](https://user-images.githubusercontent.com/42754652/53697833-2a1ba680-3dde-11e9-895f-b3c7953c5dbc.jpg)

**Comment by supercoolsonic** [comment]
Fixed.
